"""Export the trained value net into agent/vnet_weights.py (base64 npz literal).

The submitted main.py cannot assume torch on the Kaggle worker, so the value net
ships as numpy weights embedded in source: this script reads a train/value_net.py
run dir (best.pt, a torch zip — loaded here WITHOUT torch via
agent/vnet_infer.ValueFn.from_checkpoint, verified bitwise-equal to torch.load),
serialises it to a compressed npz, and writes ``VNET_B64 = "..."`` plus a
provenance comment into agent/vnet_weights.py.  The packaged agent then does
``ValueFn.from_embedded(VNET_B64)`` and never touches the filesystem.

float16 vs float32 is DECIDED BY MEASUREMENT, not assumption: both payloads are
round-tripped through from_embedded and scored against a torch reference (the
exact val_pred() formula of train/value_net.py) on real rows from the collected
shards; float16 is picked only if its max |V_torch - V_numpy| stays under
--fp16-limit ($5 — noise floor context: episode-reward sd is ~4.8k and the net's
own val MAE is ~$3.1k, so $5 of quantisation is 3 orders of magnitude below
signal).  Only W/B are quantised; scalers/scalars stay full precision (~1 KB).

Measured on the vnet_cem2 epoch-4 checkpoint (5760 rows, 12 shards): float32 max
err $0.0057 / 480,760 B file; float16 max err $5.30 / ~219 KB — fp16 REJECTED by
the $5 gate for that checkpoint. The decision is re-measured on every export, so
a retrained net may legitimately flip it.

agent/vnet_weights.py is generated and gitignored — rerun this script after any
value-net retrain; stale weights fail loudly at load if sim/features.py reorders
(money index comes from the embedded feature_names).  The output is a pure
function of (checkpoint bytes, shard prefix, args): the provenance comment pins
the checkpoint by sha256 instead of wall-clock time, so re-running the export on
the same inputs is byte-identical (verified 2026-08-27: two runs, same sha256;
the npz payload itself is already deterministic — numpy zips entries with the
1980 epoch date, and zlib at a fixed level is stable).

Usage:
  python scripts/export_vnet.py                         # vnet_cem2 -> agent/vnet_weights.py
  python scripts/export_vnet.py --run train/runs/vnet --dtype float32
"""

import argparse
import base64
import hashlib
import importlib.util
import io
import sys
from glob import glob
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agent.vnet_infer import ValueFn  # noqa: E402

HEADER = '''\
"""GENERATED by scripts/export_vnet.py — do not edit, gitignored.

{prov}
Load with: from agent.vnet_infer import ValueFn; vf = ValueFn.from_embedded(VNET_B64)
"""

VNET_B64 = "{b64}"
'''


def load_rows(data_dir, n_rows):
    """First >= n_rows feature rows from the collected shards, oldest first."""
    files = sorted(glob(str(Path(data_dir) / "shard-*.npz")))
    if not files:
        sys.exit(f"no shards under {data_dir}; run train/collect.py first")
    Xs, total = [], 0
    for f in files:
        z = np.load(f)
        Xs.append(z["features"])
        total += len(Xs[-1])
        if total >= n_rows:
            break
    return np.concatenate(Xs).astype(np.float32), len(Xs)


def torch_reference(raw_ckpt, X):
    """V on X exactly as train/value_net.py's val_pred computes it (fp32 CPU)."""
    import torch
    torch.set_num_threads(2)  # a CEM run owns the box; stay off its cores
    sys.path.insert(0, str(ROOT / "train"))
    from value_net import ValueNet
    ck = torch.load(io.BytesIO(raw_ckpt), map_location="cpu", weights_only=False)
    net = ValueNet(ck["d_in"], ck["hidden"])
    net.load_state_dict(ck["model_state"])
    net.eval()
    x_mean = np.asarray(ck["x_mean"], dtype=np.float32)
    x_std = np.asarray(ck["x_std"], dtype=np.float32)
    money = X[:, list(ck["feature_names"]).index("money")]
    with torch.no_grad():
        out = net(torch.from_numpy((X - x_mean) / x_std)).numpy()
    return money + (out * ck["d_std"] + ck["d_mean"])


def main():
    ap = argparse.ArgumentParser(description="Export value net -> agent/vnet_weights.py")
    ap.add_argument("--run", default=str(ROOT / "train" / "runs" / "vnet_cem2"))
    ap.add_argument("--data", default=str(ROOT / "train" / "data_cem2"),
                    help="shard dir for the parity measurement rows")
    ap.add_argument("--out", default=str(ROOT / "agent" / "vnet_weights.py"))
    ap.add_argument("--rows", type=int, default=5760,
                    help="parity sample size (>= 5000; 12 shards x 480 rows)")
    ap.add_argument("--dtype", choices=["auto", "float32", "float16"], default="auto")
    ap.add_argument("--fp16-limit", type=float, default=5.0,
                    help="max |V_torch - V_fp16| ($) allowed before falling back to fp32")
    args = ap.parse_args()

    ckpt_path = Path(args.run) / "best.pt"
    # One read -> both loaders. The trainer atomically replaces best.pt between
    # epochs, so two separate opens could compare different checkpoints.
    raw = ckpt_path.read_bytes()
    vf = ValueFn.from_checkpoint(io.BytesIO(raw))
    print(f"checkpoint {ckpt_path} ({len(raw)} bytes): "
          f"{'x'.join(str(w.shape[0]) for w in vf.W[:-1])} MLP, d_in "
          f"{vf.W[0].shape[1]}, meta {vf.meta}")

    X, n_shards = load_rows(args.data, args.rows)
    v_ref = torch_reference(raw, X)
    print(f"parity rows: {len(X)} from {n_shards} shards under {args.data}")

    results = {}
    for dtype in ("float32", "float16"):
        b64 = base64.b64encode(vf.to_npz_bytes(np.dtype(dtype))).decode("ascii")
        v_np = ValueFn.from_embedded(b64).v_batch(X)
        err = np.abs(v_np - v_ref)
        results[dtype] = {"b64": b64, "max": float(err.max()),
                          "mean": float(err.mean()),
                          "file_bytes": len(HEADER) + len(b64)}
        print(f"  {dtype}: max |V_torch - V_numpy| = ${err.max():.4f}  "
              f"mean ${err.mean():.4f}  ~file {results[dtype]['file_bytes']:,} B")

    if args.dtype != "auto":
        pick = args.dtype
    else:
        pick = "float16" if results["float16"]["max"] < args.fp16_limit else "float32"
    r = results[pick]
    print(f"picked {pick}" + ("" if args.dtype != "auto" else
          f" (fp16 max err ${results['float16']['max']:.2f} vs limit ${args.fp16_limit:.2f})"))

    # No wall-clock timestamp: the sha256 pins the exact checkpoint AND keeps
    # re-exports byte-identical (reproducibility is asserted by review tooling).
    prov = (f"run: {args.run}  epoch: {vf.meta.get('epoch')}  "
            f"val MAE: ${float(vf.meta.get('val_mae', float('nan'))):.0f}\n"
            f"dtype: {pick}  checkpoint sha256: {hashlib.sha256(raw).hexdigest()[:16]} "
            f"({len(raw)} bytes)\n"
            f"parity vs torch over {len(X)} rows ({args.data}): "
            f"max ${r['max']:.4f}  mean ${r['mean']:.4f}  "
            f"(float32: max ${results['float32']['max']:.4f})")
    out = Path(args.out)
    out.write_text(HEADER.format(prov=prov, b64=r["b64"]))

    # Validate the artifact the way the packaged agent will consume it:
    # import the generated file by path, decode, re-check parity.
    spec = importlib.util.spec_from_file_location("vnet_weights", out)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    err = np.abs(ValueFn.from_embedded(mod.VNET_B64).v_batch(X) - v_ref).max()
    assert err == r["max"], f"written file parity drifted: {err} != {r['max']}"
    print(f"wrote {out} ({out.stat().st_size:,} bytes); "
          f"re-imported and re-verified: max err ${err:.4f}")


if __name__ == "__main__":
    main()
